FROM node:8.2.1

WORKDIR /app

ADD ./package.json ./package.json
ADD ./package-lock.json ./package-lock.json

RUN npm install

ADD ./tsconfig.json ./tsconfig.json
ADD ./tslint.json ./tslint.json
ADD ./public ./public
ADD ./scripts ./scripts
#ADD ./src ./src

