#!/usr/bin/env bash

tmux new -d -s rsd-stack
tmux set-option -g mouse on
tmux set-option -s set-clipboard off
tmux bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xsel -i -b"
tmux bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xsel -i -b"
tmux split-window -h
tmux split-window -h
tmux split-window -v
tmux select-pane -t 0
tmux split-window -v
tmux select-pane -t 2
tmux split-window -v
tmux select-pane -t 0
tmux send-keys "docker run -p 27017:27017 -v `pwd`/db:/data/db mongo:3.6 --bind_ip 0.0.0.0" C-m
tmux select-pane -t 1
tmux send-keys "export \$(cat .env | xargs) && cd backend && workon rsd-backend && python entry.py" C-m
tmux select-pane -t 2
tmux send-keys "export \$(cat .env | xargs) && cd auth-github && workon rsd-github-auth && python app.py" C-m
tmux select-pane -t 3
tmux send-keys "export \$(cat .env | xargs) && cd admin && yarn start" C-m
tmux select-pane -t 4
tmux send-keys "export \$(cat .env | xargs) && cd frontend && workon rsd-frontend && python entry.py" C-m
tmux select-pane -t 5
tmux send-keys "export \$(cat .env | xargs) && cd tasks-nlesc && workon rsd-tasks" C-m "python app.py --task "

tmux attach -t rsd-stack
